export default {
    menu: [],
    banner:[],
    categories:[],
    infor_company:[],
    overview_infor:[],
    news: [],
    materials:[],
    products:[],
    banner_product:[],
    cart:[],
    store_system: [],
    store_contact: [],
    contact: [],
}
